"""Render docs/METHODOLOGY_V3.md from shared/config/audit_methodology_v3.json.

Usage: python scripts/render_methodology_doc.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.gtm_audit.methodology_v3.config import Methodology, load_methodology  # noqa: E402

OUTPUT = ROOT / "docs" / "METHODOLOGY_V3.md"
SEVERITY_MEANINGS = {
    "critical": "Blocks a key task or excludes a user group; no workaround",
    "high": "Seriously hampers a key task; workaround exists",
    "medium": "Friction or confusion; task still completes",
    "low": "Cosmetic / polish",
}


def _cell(value: str) -> str:
    return value.replace("|", "\\|")


def render(methodology: Methodology) -> str:
    lines = [
        "# UX/UI Audit Methodology v3 — Reference",
        "",
        "<!-- Generated by scripts/render_methodology_doc.py from shared/config/audit_methodology_v3.json. Do not edit by hand. -->",
        "",
        "Design and rationale: [methodology v3 spec](superpowers/specs/2026-10-05-ux-audit-methodology-v3-design.md).",
        "",
        "## Severity",
        "",
        "| Level | Penalty | Meaning |",
        "|---|---|---|",
    ]
    for level, meaning in SEVERITY_MEANINGS.items():
        lines.append(f"| {level.capitalize()} | {methodology.scoring.penalties[level]} | {meaning} |")
    lines += [
        "",
        "A finding on a declared key-task path is escalated one level (ceiling: Critical).",
        "",
        "## Maturity levels",
        "",
        "| Level | Label | Minimum score | Cap rule |",
        "|---|---|---|---|",
    ]
    caps = {5: "Requires no High or Critical", 4: "Requires no Critical", 2: "Any Critical caps the axis here"}
    for band in methodology.scoring.maturity_bands:
        lines.append(f"| {band.level} | {band.label.en} | {band.min_score} | {caps.get(band.level, '—')} |")
    lines += [
        "",
        f"AI-assessed findings count toward a score only at confidence ≥ {methodology.scoring.ai_confidence_gate:g} with cited elements or a screenshot region.",
        "",
        "## Product-type weights",
        "",
        "Axes not listed weigh 1.0. An unknown or missing product type uses equal weights.",
        "",
        "| Product type | Weights |",
        "|---|---|",
    ]
    for product_type, weights in methodology.product_type_weights.items():
        lines.append(f"| {product_type} | {', '.join(f'{axis} {weight:g}' for axis, weight in weights.items())} |")
    for index, axis in enumerate(methodology.axes, start=1):
        lines += [
            "",
            f"## {index}. {axis.name.en} (`{axis.id}`)",
            "",
            f"**Core question:** {axis.core_question.en}",
            "",
            "| Criterion | Title | Weight | Standards | Targets | Evidence |",
            "|---|---|---|---|---|---|",
        ]
        for criterion in axis.criteria:
            lines.append(
                f"| `{criterion.id}` | {_cell(criterion.title.en)} | {criterion.weight} | "
                f"{', '.join(criterion.standards)} | {', '.join(criterion.targets)} | {criterion.evidence_type} |"
            )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT.write_text(render(load_methodology()), encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
